version: '3'
services:
  server:
    build: ./server
    ports:
      - "3000:3000"
  client:
    build: ./client
    ports:
      - "80:80"
  service:
    build: ./service
    ports:
      - "8080:8080"
